---
title: "Übungsaufgaben R-Tutorium"
date: "Sommersemester 2021"
output:
  rmarkdown::html_document:
    theme: cosmo
    number_sections: true
  pdf_document: 
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, fig.align = "center", out.width = '50%', 
  warning = FALSE, message = FALSE)
```

# Grundlagen

## Grundrechenarten

Führen Sie die folgenden Rechnungen aus:

$$10+25$$
$$50\cdot 2$$

$$\frac{27}{4}$$
$$500-650$$

$$2^4$$

$$\sqrt{3}\cdot 60$$

$$50 \cdot (4+2)^3$$

## Rechnungen mit Zwischenschritten

Führen Sie die folgende Rechnung aus. Speichern Sie dabei die Zwischenergebnisse
immer explizit ab und verwenden Sie sie für den nächsten Schritt weiter.
Geben sie am Ende das Gesamtergebnis aus.

\begin{align*}
a &= 10 + 25\\
b &= a \cdot 40\\
c &= b - 100\\
d &= c \cdot 3\\
e &= \sqrt{d}\\
f &= \frac{e}{1000}\\
g &= f^3
\end{align*}

*Vorsicht:* Überschreiben Sie keine `R`-spezifischen Befehle, wie z.B. `c`!

# R-Markdown

Erstellen Sie einen leeren Chunk, in dem Sie einen Kommentar einfügen.


# Datenaufbereitung

TBA

# Visualisierung

TBA

# Formalia

TBA

# Regressionsanalyse I

TBA

# Monte-Carlo-Simulationen

## Der Zentrale Grenzwertsatz

Illustrieren Sie die Funktion des zentralen Grenzwertsatzes mit Hilfe einer
MCS am Beispiel des Mittelwerts einer Uniformverteilung.

## Das Gesetz der großen Zahl

Illustrieren Sie das Gesetz der großen Zahl indem Sie aus einer Normalverteilung
Stichproben unterschiedlicher Größe ziehen und deren Varianz und Mittelwert
abbilden.

## OLS und nicht-normalverteilte Fehler

Sie haben in der Vorlesung gelernt, dass die Normalverteilung der 
Fehlerterme häufig als optionale Annahme im OLS-Framework verwenet wird.
Untersuchen Sie die Implikationen von nicht-normalverteilten Fehlertermen
auf die Verteilung des OLS-Schätzers für unterschiedliche Stichprobengrößen
mit Hilfe einer MCS und interpretieren Sie die Ergebnisse.
Beziehen Sie sich der Einfachheit halber auf ein univariates Regressionsmodell.
Um nicht-normalverteilte Fehlerterme zu generieren ziehen Sie Zufallszahlen aus
der $\chi^2$-Verteilung mit einem Freiheitsgrad und normalisieren Sie die 
Fehler, sodass sie einen Mittelwert von $0$ aufweisen (Sie können die
Funktion `scale()` verwenden).

# Regressionsanalyse II

TBA

# Regressionsanalyse III

TBA